
name:
  value: arjay

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

keyStore:
  path: keystore.jks
  password: password

logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud: DEBUG
    com:
      google:
        api:
          client: DEBUG
