server:
  port: 8222
spring:
  security:
    csrf:
      enabled: false
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://localhost:4200"
              - "https://localhost:4500"
              - "http://127.0.0.1:30055"
              - "http://a8685bbecfb704a3d9be9ff7c79d600a-1930177911.eu-north-1.elb.amazonaws.com"
              - "http://ec2-51-20-206-136.eu-north-1.compute.amazonaws.com:4200"
              - "http://ec2-13-53-224-124.eu-north-1.compute.amazonaws.com:4200"
              - "http://ec2-51-20-206-136.eu-north-1.compute.amazonaws.com:8081"
              - "http://ec2-13-53-224-124.eu-north-1.compute.amazonaws.com:8081"
              - "http://ec2-51-20-206-136.eu-north-1.compute.amazonaws.com"
              - "http://ec2-13-53-224-124.eu-north-1.compute.amazonaws.com"
              - "http://13.53.224.124:4200"
              - "http://51.20.206.136:4200"
              - "http://angular-app:4200"
              - "http://miyembro.net"
              - "http://www.miyembro.net"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # Ensures service names are lowercase
      routes:
        - id: organization-service
          uri: lb:http://ORGANIZATION-SERVICE
          predicates:
            - Path=/api/v1/organizations/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: member-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/members/**
        - id: membership-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/memberships/**
        - id: membership-type-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/membership-types/**
        - id: membership-status-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/membership-statuses/**
        - id: authentication-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: menu-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/menus/**
        - id: role-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/roles/**
        - id: event-service
          uri: lb:http://EVENT-SERVICE
          predicates:
            - Path=/api/v1/event/**
        - id: event-confirmation-service
          uri: lb:http://EVENT-SERVICE
          predicates:
            - Path=/api/v1/event-confirmation/**

token:
  secret: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V