server:
  port: 8050
  use-forward-headers: true
  forward-headers-strategy: native
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-master:5432/member
    username: arjay
    password: Miyembro24122022
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        type: TRACE
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "654581949282-dmvkqbivaa8rmvem7ipjbas30p5akkrm.apps.googleusercontent.com"
            client-secret: "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"
            scope: openid, profile, email
            redirect-uri: "https://miyembro.net"

eureka:
  instance:
    hostname: member-service
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  zipkin:
    tracing:
      enabled: true
      endpoint: http://zipkin:9411/api/v2/spans

application:
  config:
    organization-url: http://gateway-service:8222/api/v1/organizations

logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud: DEBUG
    com:
      google:
        api:
          client: DEBUG

frontend:
  base-url: https://miyembro.net