spring:
  data:
    mongodb:
      username: arjay
      password: arjay
      host: localhost
      port: 27017
      database: organization
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090


application:
  config:
    membership-type-url: http://localhost:8222/api/v1/membership-types
    membership-url: http://localhost:8222/api/v1/memberships
    member-url: http://localhost:8222/api/v1/members
    role-url: http://localhost:8222/api/v1/roles

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

