spring:
  data:
    mongodb:
      username: arjay
      password: Miyembro24122022
#      host: ec2-13-48-91-4.eu-north-1.compute.amazonaws.com
      host: mongodb
      port: 27017
      database: organization
      authentication-database: admin

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  config:
    membership-type-url: http://localhost:8222/api/v1/membership-types
    membership-url: http://localhost:8222/api/v1/memberships
    member-url: http://localhost:8222/api/v1/members
    role-url: http://localhost:8222/api/v1/roles


management:
  zipkin:
    tracing:
      enabled: true
      endpoint: http://localhost:9411/api/v2/spans